### ISSUE TITLE
Server flooding: use setTimout and custom update period

### ISSUE THREAD

**Issue by drsdre** [naifalshaye/worldclock#8]
Currently setInterval is used on a 1.5 second basis. If the server has trouble responding, within 1.5 second, it will get a second request. This can repeat itself until the server is flooded.

I suggest replace setIntveral with setTimeout which at the end of processing will call itself again (with a 1500 ms delay). When the server get's flooded, it will wait patiently until a response comes in after which it will fire again after the delay.

I also want to suggest to make the update period configurable and have Javascript do the counting and use the Ajax call to adjust the ajax time to server time.

**Comment by naifalshaye** [comment]
Done, The updating time period is now configurable.

setTimeout: Runs the function once after the timeout.
setInterval: Calls function after every duration.
